# config for google/gemma-2b-AWQ
model:
  num_layers: 18
  num_q_heads: 8
  num_kv_heads: 1 # MQA
  head_dim: 256
  block_size: 16

batch_specs:
  - "q8ks128"
  - "q8ks1"
  - "q1s8k"

backends:
  - TRITON_ATTN
  - ROCM_AITER_UNIFIED_ATTN

device: "cuda:0"
repeats: 100
warmup_iters: 100
profile_memory: false
