/* Note - For packaging reasons, do not move this file from src/include/non_abi */

#pragma once

// clang-format off

#define NVSHMEM_VENDOR_MAJOR_VERSION 3
#define NVSHMEM_VENDOR_MINOR_VERSION 2
#define NVSHMEM_VENDOR_PATCH_VERSION 5
#define NVSHMEM_VENDOR_PACKAGE_VERSION 1
#define NVSHMEM_TRANSPORT_PLUGIN_MAJOR_VERSION 3
#define NVSHMEM_TRANSPORT_PLUGIN_MINOR_VERSION 0
#define NVSHMEM_TRANSPORT_PLUGIN_PATCH_VERSION 0
#define NVSHMEM_BOOTSTRAP_PLUGIN_MAJOR_VERSION 3
#define NVSHMEM_BOOTSTRAP_PLUGIN_MINOR_VERSION 0
#define NVSHMEM_BOOTSTRAP_PLUGIN_PATCH_VERSION 0
#define NVSHMEM_BUILD_VARS 

// clang-format on
