name: Test Hello World

on:
  pull_request:
    branches:
      - gfx11
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello from gfx11! This is a test PR."
